[package]
name = "quickmaths"
description = "A collection of algorithims for generic mathematics"
version = "0.1.1"
edition = "2021"
license = "MIT"

[features]
default = ["std"]
std = []

[dependencies]
num = "0.4.0"
rand = "0.8.5"

[dev-dependencies]
approx = "0.5.1"
